name: pyinn-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.0
  - numpy=1.26.4
  - pyyaml=6.0
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - matplotlib=3.6.2
  - pandas=1.5.3
  - pytorch=2.0.1
  - torchvision=0.15.2
      