name: pyinn-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10,<3.12
  - numpy>=1.24
  - pyyaml>=6.0
  - scipy>=1.10
  - scikit-learn>=1.2
  - matplotlib>=3.6
  - pandas>=1.5
  - pytorch>=2.0
  - torchvision>=0.15
  - pip
  - pip:
    - jax[cpu]>=0.4.0
    - jaxlib>=0.4.0
    - optax>=0.1.0
    - pyinn
      