name: pyinn-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.13.0
  - numpy==2.1.3
  - scipy==1.14.1
  - scikit-learn=1.5.2
  - matplotlib==3.9.2
  - pip==23.2.1
  - pandas=2.2.3
  - pytorch==2.3.1
  - torchvision==0.18.1
      