name: pyinn-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy==2.1.3
  - scipy==1.14.1
  - matplotlib==3.9.2
  - pip==23.2.1
  - pandas=2.2.3
  - pytorch==2.3.1
  - torchvision==0.18.1


  - pip:
      - optax==0.2.4
      