MODEL_PARAM: 
  
  ## INN linear
  nmode : 1
  nseg : 5 # nnode = nelem + 1

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 3
  nneurons : 6
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  
  input_col : [0]
  output_col : [1,2]
  
  bool_data_generation : True # data is already stored and splitted
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15] # [0.7,0.15,0.15]
  
  bool_normalize: False # whether we normalize the input data or not
  bool_shuffle : True # whether we shuffle the data
  

TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 100
  batch_size : 128
  learning_rate : 1e-3
  bool_train_acc : True
  
  validation_period : 1
  bool_denormalize: False # or True, whether we denormalize when measuring errors
  error_type : "mse" # rmse or mse
  patience : 10


PLOT:
  bool_plot: True
  plot_in_axis: [0] # plot input axis
  plot_out_axis: [0,1] # plot output axis