MODEL_PARAM: 
  
  ## INN linear
  nmode : [20,20,20,20,20, 20,20,20,20,20, 20,20,20,20,20, 20,20,20,20,20, 20,20,20,20,20, 20,20,20,20,20]
  nelem : 40
  # nelem : [20,25]

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 1  
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential' 
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 5
  nneurons : 100
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:

  input_col : [0,1,2]
  output_col : [3,4]

  bool_data_generation : False # data is already stored and splitted
  data_filenames: ['2D_turbulence.csv'] # original data
  # data_size: 10_000
  split_ratio: [0.8,0.10,0.10] # [0.7,0.15,0.15]
  
  bool_normalize: True # whether we normalize the input data or not
  bool_shuffle : True # whether we shuffle the data
  
  
TRAIN_PARAM:
  num_epochs_INN : 10
  num_epochs_MLP : 500
  batch_size : 128
  learning_rate : 1e-3
  # bool_train_acc : True
  
  validation_period : 1
  bool_denormalize: False # or True, whether we denormalize when measuring errors
  error_type : "rmse" # or mse
  patience : 5


PLOT:
  bool_plot: True
  plot_in_axis: [0,1] # plot input axis
  plot_out_axis: [0] # plot output axis