MODEL_PARAM: 

  ## INN linear
  nmode : 400 # 50, 100, 200, 300, 400
  nseg : 20 # 
  # nseg : [100,50,40,100,50,40] # for variable discretization

  ## INN nonlinear
  s_patch : 4
  alpha_dil: 20
  p_order: 1
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial' 
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 3
  nneurons : 400 # 50, 100, 200, 300, 400
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  input_col : [1,2,3,4,5,6]
  output_col : [7,8,9,10]
  
  bool_data_generation : False # data is already stored and splitted
  # data_filenames: ['6D_4D_ansys_train.csv', '6D_4D_ansys_test.csv']
  data_filenames: ['6D_4D_ansys_1364742.csv'] # original data
  split_ratio: [0.7,0.15,0.15] # [0.7,0.15,0.15]

  bool_normalize: True # whether we normalize the input data or not
  bool_shuffle : True # whether we shuffle the data
  
  
TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 1000
  batch_size : 128 # 128
  learning_rate : 1e-3
  bool_train_acc : False
  
  validation_period : 1 # if this is greater than num_epochs, validation will not be conducted
  bool_denormalize: False # or True, whether we denormalize when measuring errors
  error_type : "rmse" # rmse or mse
  patience : 100
  stopping_loss_train: 6e-3

PLOT:
  bool_plot: True
  plot_in_axis: [3,4] # plot input axis
  plot_out_axis: [0] # plot output axis