MODEL_PARAM: 

  ## INN linear
  nmode : 50
  nelem : 20 

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial' 
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 3
  nneurons : 50
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  input_col : [1,2,3,4,5,6]
  output_col : [10] # [7,8,9,10]
  bool_normalize: True # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  # data_size: 1364742 # 29285 
  data_size: 497
  split_ratio: [0.7,0.15,0.15] # [0.8,0.2] # [0.7,0.15,0.15]
  
TRAIN_PARAM:
  num_epochs_INN : 50
  num_epochs_MLP : 50
  batch_size : 128 # 128
  learning_rate : 1e-3
  bool_train_acc : False
  
  validation_period : 100 # if this is greater than num_epochs, validation will not be conducted
  bool_denormalize: False # or True, whether we denormalize when measuring errors
  error_type : "rmse" # or mse
  patience : 5

PLOT:
  bool_plot: True
  plot_in_axis: [3,4] # plot input axis
  plot_out_axis: [0] # plot output axis