MODEL_PARAM: 
  
  ## INN
  nmode : 10
  nelem : 20

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2  

  ## MLP
  nlayers : 3
  nneurons : 20
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  input_col : [0,1]
  output_col : [2,3]
  bool_normalize: False
  bool_random_split : True
  data_size: 10_000
  split_ratio: [0.7,0.15,0.15]
  
TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 200
  batch_size : 50
  learning_rate : 1e-3
  bool_train_acc : True
  validation_period : 1

PLOT:
  bool_plot: True
  plot_in_axis: [0,1] # plot input axis
  plot_out_axis: [0] # plot output axis