MODEL_PARAM: 
  
  ## INN linear
  nmode : 50
  nelem : 20

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2  
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP grid search
  nlayers : 5
  nneurons : 40
  activation : "relu"
  # activation : "sigmoid"

DATA_PARAM:
  input_col : [0,1,2,3,4] #x,y,z,t,k
  output_col : [5] #u
  bool_normalize: True # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  bool_load_data: False
  data_size: 1120581
  split_ratio: [0.7,0.15,0.15]

TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 300
  batch_size : 4096
  learning_rate : 1e-3
  bool_train_acc : True
  validation_period : 10

PLOT:
  bool_plot: False
  plot_in_axis: [0,1,2] # plot input axis
  plot_out_axis: [0] # plot output axis