#without r
MODEL_PARAM: 
  
  ## INN linear
  nmode : 30
  nelem : 40

  ## INN nonlinear
  s_patch : 2
  alpha_dil: 20
  p_order: 2  
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 5
  nneurons : 20
  # activation : "relu"
  activation : "sigmoid"


  ## MLP
  nlayers_cp : 5
  nneurons_cp : 20
  # activation_cp : "relu"
  activation_cp : "relu"


DATA_PARAM:
  input_col : [0,1,2,3,4,5]
  output_col : [6]
  bool_normalize: True # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  bool_load_data: True
  dataset_ratio: 0.3
  path_data: '/mnt/b/xxd5545/parse_dataset'
  data_size: 0
  split_ratio: [0]

TRAIN_PARAM:
  num_epochs_INN : 1000
  num_epochs_MLP : 1000
  batch_size : 1616293
  learning_rate : 1e-3
  bool_train_acc : True
  validation_period : 10

PLOT:
  bool_plot: True
  plot_in_axis: [0,1,2] # plot input axis
  plot_out_axis: [0] # plot output axis