MODEL_PARAM: 

  ## INN linear
  nmode : 60
  nelem : 40
  # nelem : [10,12,14,16,10,10,10,10,20,23] # for variable discretization

  ## INN nonlinear
  s_patch : 4
  alpha_dil: 20
  p_order: 1
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 5
  nneurons : 60
  # activation : "relu"
  activation : "sigmoid"

DATA_PARAM:
  
  input_col : [0,1,2,3,4] # 0,1 for x,y ; 2,3 for k,P; 4 for time
  output_col : [5] # temperature
  
  bool_data_generation : False # data is already stored and splitted
  data_filenames: ['/mnt/a/jgz1751/icml_parse_dataset/train_clean.csv', '/mnt/a/jgz1751/icml_parse_dataset/val_clean.csv', '/mnt/a/jgz1751/icml_parse_dataset/test_clean.csv']
  # data_size: 100_000
  # split_ratio: [0.8,0.2] # [0.7,0.15,0.15]

  bool_normalize: True # whether we normalize the input data or not
  bool_shuffle : True # whether we randomly split the data or not
  
TRAIN_PARAM:
  num_epochs_INN : 100
  num_epochs_MLP : 100
  batch_size : 512 # 128
  learning_rate : 1e-4
  bool_train_acc : False
  
  validation_period : 1 # if this is greater than num_epochs, validation will not be conducted
  bool_denormalize: False # or True, whether we denormalize when measuring errors
  error_type : "rmse" # or mse
  patience : 5 # for early stopping

  stopping_loss_train: 4e-8


PLOT:
  bool_plot: True
  plot_in_axis: [3,4,5,6] # plot input axis
  plot_out_axis: [0] # plot output axis