#without r
MODEL_PARAM: 
  
  ## INN linear
  nmode : 60
  nelem : 40

  ## INN nonlinear
  s_patch : 4
  alpha_dil: 20
  p_order: 1 
  radial_basis : "cubicSpline" # Activataion functions
  # radial_basis : 'gaussian1'
  INNactivation : 'polynomial'
  # INNactivation : 'sinusoidal'
  # INNactivation : 'exponential'
  # INNactivation : 'sigmoid'
  # INNactivation : 'tanh'
  # INNactivation : 'gelu'

  ## MLP
  nlayers : 5
  nneurons : 50
  activation : "relu"
  # activation : "sigmoid"


  ## CPMLP
  nlayers_cp : 1
  nneurons_cp : 20
  # activation_cp : "relu" #7380
  activation_cp : "relu"


DATA_PARAM:
  input_col : [0,1,2,3,4] # 0,1 for x,y ; 2,3 for k,P; 4 for time
  output_col : [5] # temperature
  bool_normalize: True # whether we normalize the input data or not
  bool_random_split : True # whether we randomly split the data or not
  bool_load_data: True
  dataset_ratio: 1
  path_data: '/mnt/a/jgz1751/icml_parse_dataset'
  data_size: 0
  # data_noise: "clean" # noisy
  data_noise: "noisy" # noisy
  split_ratio: [0]

TRAIN_PARAM:
  num_epochs_INN : 2000
  num_epochs_MLP : 2000
  batch_size : 128 #how to determine the batch size?
  learning_rate : 1e-4
  bool_train_acc : True
  validation_period : 200
  patience : 10

PLOT:
  bool_plot: False
  plot_in_axis: [0,1,2] # plot input axis
  plot_out_axis: [0] # plot output axis